  
FROM node:alpine as build

WORKDIR /app

# Install yarn and other dependencies via apk
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*


COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .

RUN yarn build

# 2 - stage for deploy production
FROM nginx:1.15.2-alpine
COPY --from=build /app/build/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

RUN apk add --no-cache bash